name: Create html web documentation

on: push
  
jobs:
  docs:
    runs-on: ubuntu-latest

    steps:

    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools Displacement-strain-planet sphinx_rtd_theme sphinx

    - name: Build the sphinx documentation
      shell: bash -l {0}
      run: |
        cd docs
        make html

    - name: Upload artifact of the html output
      uses: actions/upload-artifact@v2
      with:
        name: gh-pages-documentation
        path: docs/_build/html/
        retention-days: 1
    
    - name: Clean gh-pages branch
      shell: bash -l {0}
      run: |
        git config --local user.email "adrien.broquet@oca.eu"
        git config --local user.name "GitHub Action"
        git switch gh-pages
        git config --local user.email "adrien.broquet@oca.eu"
        git config --local user.name "GitHub Action"

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: gh-pages-documentation

    - name: Commit changes
      shell: bash -l {0}
      run: |
        git add .
        git commit -m "Update gh-pages documentation" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
